// <auto-generated />
using MVCCoreCRUDwithEFCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCCoreCRUDwithEFCore.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20190403161802_AddNhanVien")]
    partial class AddNhanVien
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCCoreCRUDwithEFCore.Models.NhanVien", b =>
                {
                    b.Property<int>("NhanVienId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("MucLuong");

                    b.Property<string>("NoiLamViec")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("NhanVienId");

                    b.ToTable("NhanVien");
                });
#pragma warning restore 612, 618
        }
    }
}
